const { use, replaceDb, dbPath, countChars, sanitize, cnToNum, parseStoryTimeValue } = require('./services/common')
const { authCheck, registerUser, loginUser, changePassword, disableAuth } = require('./services/auth')
const { listNovels, createNovel, getNovel, updateNovel, deleteNovel } = require('./services/novels')
const {
  listChapters,
  getChapter,
  importDocxAsChapter,
  createChapter,
  updateChapter,
  deleteChapter,
  batchDeleteChapters,
  batchUpdateChapters,
  reorderChapters,
} = require('./services/chapters')
const { listVersions, saveVersion, getVersionContent, deleteVersions } = require('./services/versions')
const { listOutlines, createOutline, updateOutline, deleteOutline } = require('./services/outlines')
const { listCharacters, createCharacter, updateCharacter, deleteCharacter } = require('./services/characters')
const { listWorlds, listWorldNames, createWorld, updateWorld, deleteWorld } = require('./services/worlds')
const {
  listMaterials,
  queryMaterials,
  getMaterialById,
  getMaterialTypes,
  createMaterial,
  updateMaterial,
  deleteMaterial,
} = require('./services/materials')
const { getSetting, setSetting } = require('./services/settings')
const { getShortcuts, setShortcuts } = require('./services/shortcuts')
const {
  addTypingWords,
  getTypingStats,
  resetTypingSession,
  getWritingStreak,
  addFocusSession,
  getFocusStats,
} = require('./services/typing')
const { logAiUsage, getAiUsage, clearAiUsage } = require('./services/ai-usage')
const { listTypoDict, addTypo, updateTypo, deleteTypo, getTypoRecords, clearTypoRecords } = require('./services/typo')
const {
  FORESHADOW_TYPES,
  listForeshadowings,
  createForeshadowing,
  updateForeshadowing,
  deleteForeshadowing,
} = require('./services/foreshadowings')
const {
  listTimeline,
  createTimelineEvent,
  updateTimelineEvent,
  deleteTimelineEvent,
  reorderTimeline,
  sortTimelineByStoryTime,
} = require('./services/timeline')
const { listRelations, createRelation, updateRelation, deleteRelation } = require('./services/relations')
const { listItems, createItem, updateItem, deleteItem } = require('./services/items')
const {
  listWorldRules,
  listRuleEras,
  listCustomEras,
  addCustomEra,
  createWorldRule,
  updateWorldRule,
  deleteWorldRule,
} = require('./services/world-rules')
const { listPrompts, createPrompt, updatePrompt, deletePrompt } = require('./services/prompts')
const { getStats } = require('./services/stats')
const { fullTextSearch, replaceInChapters } = require('./services/search')
const {
  materialBatchImport,
  exportDocx,
  exportNovel,
  importNovel,
  backupNovel,
  autoBackupAll,
} = require('./services/export')

module.exports = {
  use,
  replaceDb,
  dbPath,
  countChars,
  sanitize,
  cnToNum,
  parseStoryTimeValue,
  listNovels,
  createNovel,
  getNovel,
  updateNovel,
  deleteNovel,
  listChapters,
  getChapter,
  importDocxAsChapter,
  createChapter,
  updateChapter,
  deleteChapter,
  batchDeleteChapters,
  batchUpdateChapters,
  reorderChapters,
  listVersions,
  saveVersion,
  getVersionContent,
  deleteVersions,
  listOutlines,
  createOutline,
  updateOutline,
  deleteOutline,
  listCharacters,
  createCharacter,
  updateCharacter,
  deleteCharacter,
  listWorlds,
  listWorldNames,
  createWorld,
  updateWorld,
  deleteWorld,
  listMaterials,
  queryMaterials,
  getMaterialById,
  getMaterialTypes,
  createMaterial,
  updateMaterial,
  deleteMaterial,
  getSetting,
  setSetting,
  getShortcuts,
  setShortcuts,
  addTypingWords,
  getTypingStats,
  resetTypingSession,
  getWritingStreak,
  addFocusSession,
  getFocusStats,
  logAiUsage,
  getAiUsage,
  clearAiUsage,
  authCheck,
  registerUser,
  loginUser,
  changePassword,
  disableAuth,
  listTypoDict,
  addTypo,
  updateTypo,
  deleteTypo,
  getTypoRecords,
  clearTypoRecords,
  FORESHADOW_TYPES,
  listForeshadowings,
  createForeshadowing,
  updateForeshadowing,
  deleteForeshadowing,
  listTimeline,
  createTimelineEvent,
  updateTimelineEvent,
  deleteTimelineEvent,
  reorderTimeline,
  sortTimelineByStoryTime,
  listRelations,
  createRelation,
  updateRelation,
  deleteRelation,
  listItems,
  createItem,
  updateItem,
  deleteItem,
  listWorldRules,
  listRuleEras,
  listCustomEras,
  addCustomEra,
  createWorldRule,
  updateWorldRule,
  deleteWorldRule,
  listPrompts,
  createPrompt,
  updatePrompt,
  deletePrompt,
  getStats,
  fullTextSearch,
  replaceInChapters,
  materialBatchImport,
  exportDocx,
  exportNovel,
  importNovel,
  backupNovel,
  autoBackupAll,
}
